export const departments = [
  { name: "Agricultural Economics", faculty: "Agriculture" },
  { name: "Food Science and Technology", faculty: "Agriculture" },
  { name: "Agricultural Extension and Rural Development", faculty: "Agriculture" },
  { name: "Animal Science", faculty: "Agriculture" },
  { name: "Crop Science", faculty: "Agriculture" },
  { name: "Soil Science", faculty: "Agriculture" },
  {name: 'Arabic and Islamic Studies', faculty: 'Arts'},
  {name: 'Mass Communication', faculty: 'Arts'},
  {name: 'Fine and Applied Arts', faculty: 'Arts'},
  {name: 'English and Literary Studies', faculty: 'Arts'},
  {name: 'History and International Studies', faculty: 'Arts'},
  {name: 'Linguistics and Communication Studies', faculty: 'Arts'},
  {name: 'Botany', faculty: 'Biological Sciences'},
  {name: 'Microbiology', faculty: 'Biological Sciences'},
  {name: 'Biochemistry', faculty: 'Biological Sciences'},
  {name: 'Zoology', faculty: 'Biological Sciences'},
  {name: 'Business Administration', faculty: 'Management Studies'},
  {name: 'Accountancy', faculty: 'Management Studies'},
  {name: 'Banking and Finance', faculty: 'Management Studies'},
  {name: 'Marketing', faculty: 'Management Studies'},
  {name: 'Public Administration', faculty: 'Management Studies'},
  {name: 'Arts Education',faculty: 'Education'},
  {name: 'Science Education',faculty: 'Education'},
  {name: 'Social Science Education',faculty: 'Education'},
  {name: 'Education and Mathematics',faculty: 'Education'},
  {name: 'Education and Physics',faculty: 'Education'},
  {name: 'Education and Chemistry',faculty: 'Education'},
  {name: 'Education and Biology',faculty: 'Education'},
  {name: 'Civil Engineering', faculty: 'Engineering'},
  {name: 'Electrical/Electronics Engineering', faculty: 'Engineering'},
  {name: 'Mechanical Engineering', faculty: 'Engineering'},
  {name: 'Chemical Engineering', faculty: 'Engineering'},
  {name: 'Computer Engineering', faculty: 'Engineering'},
  {name: 'Petroleum Engineering', faculty: 'Engineering'},
  {name: 'Law', faculty: 'Law'},
  {name: 'Economics', faculty: 'Social Sciences'},
  {name: 'Political Science', faculty: 'Social Sciences'},
  {name: 'Sociology', faculty: 'Social Sciences'},
  {name: 'Psychology', faculty: 'Social Sciences'},
  {name: 'Geography and Environmental Management', faculty: 'Social Sciences'},
  {name: 'Geology', faculty: 'Physical Sciences'},
  {name: 'Physics', faculty: 'Physical Sciences'},
  {name: 'Chemistry', faculty: 'Physical Sciences'},
  {name: 'Mathematics', faculty: 'Physical Sciences'},
  {name: 'Statistics', faculty: 'Physical Sciences'},
  {name: 'Computer Science', faculty: 'Physical Sciences'},
  {name: 'Industrial Chemistry', faculty: 'Physical Sciences'},
  {name: 'Industrial Physics', faculty: 'Physical Sciences'},
];

export const faculties = [
  "Agriculture",
  "Arts",
  "Biological Sciences",
  "Management Studies",
  "Medical Sciences",
  "Education",
  "Engineering",
  "Law",
  "Social Sciences",
  "Physical Sciences",
];
